# Generated by Django 2.0.3 on 2018-06-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='Электронный адрес для отправки чека покупателю')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон покупателя')),
                ('taxation', models.CharField(choices=[('osn', 'общая СН'), ('usn_income', 'упрощенная СН (доходы)'), ('usn_income_outcome', 'упрощенная СН (доходы минус расходы)'), ('envd', 'единый налог на вмененный доход'), ('esn', 'единый сельскохозяйственный налог'), ('patent', 'патентная СН')], max_length=20, verbose_name='Система налогообложения')),
            ],
            options={
                'verbose_name_plural': 'Данные чеков',
                'verbose_name': 'Данные чека',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование товара')),
                ('price', models.IntegerField(verbose_name='Цена в копейках')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Количество/вес')),
                ('amount', models.IntegerField(verbose_name='Сумма в копейках')),
                ('tax', models.CharField(choices=[('none', 'без НДС'), ('vat0', 'НДС по ставке 0%'), ('vat10', 'НДС чека по ставке 10%'), ('vat18', 'НДС чека по ставке 18%'), ('vat110', 'НДС чека по расчетной ставке 10/110'), ('vat118', 'НДС чека по расчетной ставке 18/118')], max_length=10, verbose_name='Ставка налога')),
                ('ean13', models.CharField(blank=True, default='', max_length=20, verbose_name='Штрих-код')),
                ('shop_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Код магазина')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.Receipt', verbose_name='Чек')),
            ],
            options={
                'verbose_name_plural': 'Информация о товарах',
                'verbose_name': 'Информация о товаре',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Уникальный идентификатор транзакции в системе банка'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.Payment', verbose_name='Платеж'),
        ),
    ]
