# Generated by Django 2.0.3 on 2018-06-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0002_auto_20180602_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.Payment', verbose_name='Платеж'),
        ),
    ]
