# Generated by Django 2.0.3 on 2018-06-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0003_auto_20180602_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
